import type { Species } from './ecosystem';

const commons = (path: string) => `https://upload.wikimedia.org/wikipedia/commons/thumb/${path}`;
const credit = (file: string) => `https://commons.wikimedia.org/wiki/File:${file}`;

/** Curated reference species. Photos are from Wikimedia Commons. */
export const CATALOG: Species[] = [
  {
    id: 'bengal-tiger',
    common_name: 'Bengal Tiger',
    scientific_name: 'Panthera tigris tigris',
    description:
      'The largest cat of the Indian subcontinent. A single tiger needs a territory large enough to hold hundreds of deer, so a healthy tiger population signals a healthy forest.',
    image_url: commons('8/84/Bengal_tiger_in_Sanjay_Dubri_Tiger_Reserve_December_2024_by_Tisha_Mukherjee_11.jpg/960px-Bengal_tiger_in_Sanjay_Dubri_Tiger_Reserve_December_2024_by_Tisha_Mukherjee_11.jpg'),
    image_credit: credit('Bengal_tiger_in_Sanjay_Dubri_Tiger_Reserve_December_2024_by_Tisha_Mukherjee_11.jpg'),
    habitat: 'Forest',
    region: 'Central India',
    status: 'EN',
    latitude: 23.17,
    longitude: 79.93,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Carnivora', family: 'Felidae', genus: 'Panthera' },
    ecological_role: 'Apex predator. Keeps deer and wild boar numbers in check, which protects forest regeneration.',
    dependencies: ['Chital', 'Sambar', 'Sal forest'],
    field_notes: ['No two tigers share the same stripe pattern.', 'India holds roughly three quarters of the world’s wild tigers.'],
  },
  {
    id: 'red-panda',
    common_name: 'Red Panda',
    scientific_name: 'Ailurus fulgens',
    description:
      'A tree-dwelling mammal of the eastern Himalayas that feeds almost entirely on bamboo leaves, spending most of its day resting in the canopy.',
    image_url: commons('f/fd/Red_Panda%2C_Gentle_Tree-Dweller_of_the_Himalayas.jpg/960px-Red_Panda%2C_Gentle_Tree-Dweller_of_the_Himalayas.jpg'),
    image_credit: credit('Red_Panda,_Gentle_Tree-Dweller_of_the_Himalayas.jpg'),
    habitat: 'Mountain',
    region: 'Eastern Himalayas',
    status: 'EN',
    latitude: 27.33,
    longitude: 88.39,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Carnivora', family: 'Ailuridae', genus: 'Ailurus' },
    ecological_role: 'Indicator of temperate bamboo forest health; disperses seeds of the fruits it occasionally eats.',
    dependencies: ['Bamboo', 'Rhododendron forest'],
    field_notes: ['It is the only living member of its family, Ailuridae.', 'A false thumb, an extended wrist bone, helps it grip bamboo.'],
  },
  {
    id: 'ganges-river-dolphin',
    common_name: 'Ganges River Dolphin',
    scientific_name: 'Platanista gangetica',
    description:
      'A nearly blind freshwater dolphin that hunts by echolocation in the muddy waters of the Ganges and Brahmaputra river systems. India’s national aquatic animal.',
    image_url: commons('8/81/Ganges_River_Dolphin_cropped.jpg/960px-Ganges_River_Dolphin_cropped.jpg'),
    image_credit: credit('Ganges_River_Dolphin_cropped.jpg'),
    habitat: 'Wetland',
    region: 'Ganges Basin',
    status: 'EN',
    latitude: 25.59,
    longitude: 85.13,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Artiodactyla', family: 'Platanistidae', genus: 'Platanista' },
    ecological_role: 'Top predator of the river channel; its presence indicates clean, free-flowing water.',
    dependencies: ['Freshwater fish', 'River prawns'],
    field_notes: ['Its eyes lack a lens, so it senses little more than light.', 'Locally called “susu” after the sound it makes when surfacing.'],
  },
  {
    id: 'snow-leopard',
    common_name: 'Snow Leopard',
    scientific_name: 'Panthera uncia',
    description:
      'A pale, heavily furred cat of high Himalayan slopes, rarely seen and able to take prey three times its own weight on near-vertical terrain.',
    image_url: commons('a/a5/Irbis4.JPG/960px-Irbis4.JPG'),
    image_credit: credit('Irbis4.JPG'),
    habitat: 'Mountain',
    region: 'Western Himalayas',
    status: 'VU',
    latitude: 34.15,
    longitude: 77.58,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Carnivora', family: 'Felidae', genus: 'Panthera' },
    ecological_role: 'Apex predator of the alpine zone, regulating wild sheep and goat populations that would otherwise overgraze.',
    dependencies: ['Bharal', 'Himalayan ibex', 'Alpine meadows'],
    field_notes: ['It wraps its long tail around its face for warmth.', 'Snow leopards cannot roar.'],
  },
  {
    id: 'indian-rhinoceros',
    common_name: 'Indian Rhinoceros',
    scientific_name: 'Rhinoceros unicornis',
    description:
      'The greater one-horned rhino of the Brahmaputra floodplains. Once reduced to about 200 animals, it has recovered to over 4,000 through strict protection.',
    image_url: commons('7/77/Great-Indian-one-horned-rhinoceros-at-Kaziranga-national-park-in-Assam-India.jpg/960px-Great-Indian-one-horned-rhinoceros-at-Kaziranga-national-park-in-Assam-India.jpg'),
    image_credit: credit('Great-Indian-one-horned-rhinoceros-at-Kaziranga-national-park-in-Assam-India.jpg'),
    habitat: 'Grassland',
    region: 'Northeast India',
    status: 'VU',
    latitude: 26.58,
    longitude: 93.17,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Perissodactyla', family: 'Rhinocerotidae', genus: 'Rhinoceros' },
    ecological_role: 'Mega-grazer that keeps tall floodplain grassland open and spreads seeds in its dung.',
    dependencies: ['Elephant grass', 'Floodplain wetlands'],
    field_notes: ['Kaziranga National Park holds about two thirds of the world population.'],
  },
  {
    id: 'asian-elephant',
    common_name: 'Asian Elephant',
    scientific_name: 'Elephas maximus',
    description:
      'The largest land animal in Asia. Herds travel long seasonal routes through forest corridors, eating up to 150 kg of vegetation a day.',
    image_url: commons('9/98/Elephas_maximus_%28Bandipur%29.jpg/960px-Elephas_maximus_%28Bandipur%29.jpg'),
    image_credit: credit('Elephas_maximus_(Bandipur).jpg'),
    habitat: 'Forest',
    region: 'Western Ghats',
    status: 'EN',
    latitude: 11.66,
    longitude: 76.63,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Proboscidea', family: 'Elephantidae', genus: 'Elephas' },
    ecological_role: 'Ecosystem engineer: opens paths and clearings, and carries large seeds for kilometres.',
    dependencies: ['Bamboo', 'Fig trees', 'Forest corridors'],
    field_notes: ['Elephants communicate with rumbles below the range of human hearing.'],
  },
  {
    id: 'great-hornbill',
    common_name: 'Great Hornbill',
    scientific_name: 'Buceros bicornis',
    description:
      'A huge fruit-eating bird with a yellow casque. The female seals herself inside a tree cavity to nest, and the male feeds her through a narrow slit.',
    image_url: commons('e/ee/Great_hornbill_Photograph_by_Shantanu_Kuveskar.jpg/960px-Great_hornbill_Photograph_by_Shantanu_Kuveskar.jpg'),
    image_credit: credit('Great_hornbill_Photograph_by_Shantanu_Kuveskar.jpg'),
    habitat: 'Forest',
    region: 'Western Ghats',
    status: 'VU',
    latitude: 10.35,
    longitude: 76.75,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Aves', order: 'Bucerotiformes', family: 'Bucerotidae', genus: 'Buceros' },
    ecological_role: 'Long-distance seed disperser for large-fruited rainforest trees.',
    dependencies: ['Fig trees', 'Old-growth nest trees'],
    field_notes: ['A pair can use the same nest cavity for many years.'],
  },
  {
    id: 'lion-tailed-macaque',
    common_name: 'Lion-tailed Macaque',
    scientific_name: 'Macaca silenus',
    description:
      'A shy monkey with a silver mane, found only in fragments of rainforest in the Western Ghats. It spends most of its life in the upper canopy.',
    image_url: commons('c/c3/Lion-tailed_Macaque_in_Bristol_Zoo.jpg/960px-Lion-tailed_Macaque_in_Bristol_Zoo.jpg'),
    image_credit: credit('Lion-tailed_Macaque_in_Bristol_Zoo.jpg'),
    habitat: 'Forest',
    region: 'Western Ghats',
    status: 'EN',
    latitude: 10.26,
    longitude: 76.93,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Primates', family: 'Cercopithecidae', genus: 'Macaca' },
    ecological_role: 'Seed disperser of rainforest fruit trees; avoids disturbed forest, so it marks intact canopy.',
    dependencies: ['Fig trees', 'Jackfruit', 'Unbroken canopy'],
    field_notes: ['Fewer than 4,000 remain in the wild.'],
  },
  {
    id: 'gharial',
    common_name: 'Gharial',
    scientific_name: 'Gavialis gangeticus',
    description:
      'A fish-eating crocodilian with a long, thin snout. Adult males grow a bulbous knob on the snout tip called a ghara, after an Indian clay pot.',
    image_url: commons('a/a7/Gharial_%28Gavialis_gangeticus%29_male.jpg/960px-Gharial_%28Gavialis_gangeticus%29_male.jpg'),
    image_credit: credit('Gharial_(Gavialis_gangeticus)_male.jpg'),
    habitat: 'Wetland',
    region: 'Chambal Valley',
    status: 'CR',
    latitude: 26.65,
    longitude: 78.35,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Reptilia', order: 'Crocodylia', family: 'Gavialidae', genus: 'Gavialis' },
    ecological_role: 'Controls fish populations in deep river pools; needs undisturbed sandbanks to nest.',
    dependencies: ['Freshwater fish', 'River sandbanks'],
    field_notes: ['The National Chambal Sanctuary is its most important stronghold.'],
  },
  {
    id: 'nilgiri-tahr',
    common_name: 'Nilgiri Tahr',
    scientific_name: 'Nilgiritragus hylocrius',
    description:
      'A stocky mountain goat of the southern Western Ghats, grazing the high grassland that caps the hills above the shola forest.',
    image_url: commons('8/89/Nilgiri_Tahr_at_Eravikulam_National_Park.jpg/960px-Nilgiri_Tahr_at_Eravikulam_National_Park.jpg'),
    image_credit: credit('Nilgiri_Tahr_at_Eravikulam_National_Park.jpg'),
    habitat: 'Grassland',
    region: 'Western Ghats',
    status: 'EN',
    latitude: 10.17,
    longitude: 77.06,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Artiodactyla', family: 'Bovidae', genus: 'Nilgiritragus' },
    ecological_role: 'Main grazer of montane grassland and key prey for leopards and dholes.',
    dependencies: ['Montane grassland', 'Shola forest'],
    field_notes: ['It is the state animal of Tamil Nadu.'],
  },
  {
    id: 'hawksbill-sea-turtle',
    common_name: 'Hawksbill Sea Turtle',
    scientific_name: 'Eretmochelys imbricata',
    description:
      'A reef-dwelling sea turtle with a sharp, bird-like beak and an overlapping, patterned shell. It nests on beaches of the Andaman and Lakshadweep islands.',
    image_url: commons('b/b0/Eretmochelys-imbricata-K%C3%A9lonia-2.JPG/960px-Eretmochelys-imbricata-K%C3%A9lonia-2.JPG'),
    image_credit: credit('Eretmochelys-imbricata-Kélonia-2.JPG'),
    habitat: 'Marine',
    region: 'Lakshadweep',
    status: 'CR',
    latitude: 10.57,
    longitude: 72.64,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Reptilia', order: 'Testudines', family: 'Cheloniidae', genus: 'Eretmochelys' },
    ecological_role: 'Eats reef sponges that would otherwise crowd out corals.',
    dependencies: ['Sea sponges', 'Coral reefs', 'Nesting beaches'],
    field_notes: ['Its shell was historically the main source of “tortoiseshell”.'],
  },
  {
    id: 'indian-pangolin',
    common_name: 'Indian Pangolin',
    scientific_name: 'Manis crassicaudata',
    description:
      'A nocturnal, scale-covered anteater that rolls into a ball when threatened. It is one of the most trafficked mammals in the world.',
    image_url: commons('3/30/Scaly_ant_eater_by_Dushy_Ranetunge_2.jpg/960px-Scaly_ant_eater_by_Dushy_Ranetunge_2.jpg'),
    image_credit: credit('Scaly_ant_eater_by_Dushy_Ranetunge_2.jpg'),
    habitat: 'Forest',
    region: 'Central India',
    status: 'EN',
    latitude: 21.15,
    longitude: 79.09,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Pholidota', family: 'Manidae', genus: 'Manis' },
    ecological_role: 'Natural pest control: a single pangolin eats tens of millions of ants and termites a year.',
    dependencies: ['Termites', 'Ants'],
    field_notes: ['Pangolins have no teeth; they swallow small stones to grind food.'],
  },
  {
    id: 'great-indian-bustard',
    common_name: 'Great Indian Bustard',
    scientific_name: 'Ardeotis nigriceps',
    description:
      'One of the heaviest flying birds, striding through dry grassland of the Thar. Collisions with power lines are now its leading cause of death.',
    image_url: commons('3/34/Ardeotis_nigriceps%2C_Desert_National_Park%2C_Rajasthan%2C_India_1.jpg/960px-Ardeotis_nigriceps%2C_Desert_National_Park%2C_Rajasthan%2C_India_1.jpg'),
    image_credit: credit('Ardeotis_nigriceps,_Desert_National_Park,_Rajasthan,_India_1.jpg'),
    habitat: 'Grassland',
    region: 'Thar Desert',
    status: 'CR',
    latitude: 26.93,
    longitude: 70.9,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Aves', order: 'Otidiformes', family: 'Otididae', genus: 'Ardeotis' },
    ecological_role: 'Flagship of arid grasslands; eats grasshoppers and other crop pests.',
    dependencies: ['Grasshoppers', 'Arid grassland'],
    field_notes: ['Fewer than 150 birds are thought to survive.'],
  },
  {
    id: 'purple-frog',
    common_name: 'Purple Frog',
    scientific_name: 'Nasikabatrachus sahyadrensis',
    description:
      'A bloated, burrowing frog that lives underground for most of the year and surfaces for only a few days of monsoon to breed.',
    image_url: commons('0/08/Nasikabatrachus_sahyadrensis.jpg/960px-Nasikabatrachus_sahyadrensis.jpg'),
    image_credit: credit('Nasikabatrachus_sahyadrensis.jpg'),
    habitat: 'Forest',
    region: 'Western Ghats',
    status: 'EN',
    latitude: 9.85,
    longitude: 76.97,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Amphibia', order: 'Anura', family: 'Nasikabatrachidae', genus: 'Nasikabatrachus' },
    ecological_role: 'Underground termite predator; its lineage split from its closest relatives in the Seychelles over 100 million years ago.',
    dependencies: ['Termites', 'Monsoon streams'],
    field_notes: ['It was only described by science in 2003.'],
  },
  {
    id: 'dugong',
    common_name: 'Dugong',
    scientific_name: 'Dugong dugon',
    description:
      'A slow, gentle marine mammal that grazes seagrass meadows in shallow coastal water. India’s largest populations are in the Gulf of Mannar and Palk Bay.',
    image_url: commons('4/42/Dugong.JPG/960px-Dugong.JPG'),
    image_credit: credit('Dugong.JPG'),
    habitat: 'Marine',
    region: 'Gulf of Mannar',
    status: 'VU',
    latitude: 9.12,
    longitude: 79.15,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Sirenia', family: 'Dugongidae', genus: 'Dugong' },
    ecological_role: 'Grazing keeps seagrass meadows productive, which in turn shelter juvenile fish.',
    dependencies: ['Seagrass meadows'],
    field_notes: ['Dugongs are more closely related to elephants than to whales.'],
  },
  {
    id: 'blackbuck',
    common_name: 'Blackbuck',
    scientific_name: 'Antilope cervicapra',
    description:
      'A fast antelope of open plains. Males turn nearly black with age and carry long spiralled horns. It has rebounded where local communities protect it.',
    image_url: commons('5/5e/Blackbuck_male_female.jpg/960px-Blackbuck_male_female.jpg'),
    image_credit: credit('Blackbuck_male_female.jpg'),
    habitat: 'Grassland',
    region: 'Western India',
    status: 'LC',
    latitude: 22.05,
    longitude: 72.03,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Artiodactyla', family: 'Bovidae', genus: 'Antilope' },
    ecological_role: 'Grazer of short grassland and prey for wolves.',
    dependencies: ['Arid grassland'],
    field_notes: ['It can run at over 80 km/h.'],
  },
];
