import type { Species } from './ecosystem';

const commons = (path: string) => `https://upload.wikimedia.org/wikipedia/commons/thumb/${path}`;
const credit = (file: string) => `https://commons.wikimedia.org/wiki/File:${file}`;

/** Curated reference species. Photos are from Wikimedia Commons. */
export const CATALOG: Species[] = [
  {
    id: 'bengal-tiger',
    kind: 'fauna',
    common_name: 'Bengal Tiger',
    scientific_name: 'Panthera tigris tigris',
    description:
      'The largest cat of the Indian subcontinent. A single tiger needs a territory large enough to hold hundreds of deer, so a healthy tiger population signals a healthy forest.',
    image_url: commons('8/84/Bengal_tiger_in_Sanjay_Dubri_Tiger_Reserve_December_2024_by_Tisha_Mukherjee_11.jpg/960px-Bengal_tiger_in_Sanjay_Dubri_Tiger_Reserve_December_2024_by_Tisha_Mukherjee_11.jpg'),
    image_credit: credit('Bengal_tiger_in_Sanjay_Dubri_Tiger_Reserve_December_2024_by_Tisha_Mukherjee_11.jpg'),
    habitat: 'Forest',
    region: 'Central India',
    status: 'EN',
    latitude: 23.17,
    longitude: 79.93,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Carnivora', family: 'Felidae', genus: 'Panthera' },
    ecological_role: 'Apex predator. Keeps deer and wild boar numbers in check, which protects forest regeneration.',
    dependencies: ['Chital', 'Sambar', 'Sal forest'],
    field_notes: ['No two tigers share the same stripe pattern.', 'India holds roughly three quarters of the world’s wild tigers.'],
  },
  {
    id: 'red-panda',
    kind: 'fauna',
    common_name: 'Red Panda',
    scientific_name: 'Ailurus fulgens',
    description:
      'A tree-dwelling mammal of the eastern Himalayas that feeds almost entirely on bamboo leaves, spending most of its day resting in the canopy.',
    image_url: commons('f/fd/Red_Panda%2C_Gentle_Tree-Dweller_of_the_Himalayas.jpg/960px-Red_Panda%2C_Gentle_Tree-Dweller_of_the_Himalayas.jpg'),
    image_credit: credit('Red_Panda,_Gentle_Tree-Dweller_of_the_Himalayas.jpg'),
    habitat: 'Mountain',
    region: 'Eastern Himalayas',
    status: 'EN',
    latitude: 27.33,
    longitude: 88.39,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Carnivora', family: 'Ailuridae', genus: 'Ailurus' },
    ecological_role: 'Indicator of temperate bamboo forest health; disperses seeds of the fruits it occasionally eats.',
    dependencies: ['Bamboo', 'Rhododendron forest'],
    field_notes: ['It is the only living member of its family, Ailuridae.', 'A false thumb, an extended wrist bone, helps it grip bamboo.'],
  },
  {
    id: 'ganges-river-dolphin',
    kind: 'fauna',
    common_name: 'Ganges River Dolphin',
    scientific_name: 'Platanista gangetica',
    description:
      'A nearly blind freshwater dolphin that hunts by echolocation in the muddy waters of the Ganges and Brahmaputra river systems. India’s national aquatic animal.',
    image_url: commons('8/81/Ganges_River_Dolphin_cropped.jpg/960px-Ganges_River_Dolphin_cropped.jpg'),
    image_credit: credit('Ganges_River_Dolphin_cropped.jpg'),
    habitat: 'Wetland',
    region: 'Ganges Basin',
    status: 'EN',
    latitude: 25.59,
    longitude: 85.13,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Artiodactyla', family: 'Platanistidae', genus: 'Platanista' },
    ecological_role: 'Top predator of the river channel; its presence indicates clean, free-flowing water.',
    dependencies: ['Freshwater fish', 'River prawns'],
    field_notes: ['Its eyes lack a lens, so it senses little more than light.', 'Locally called “susu” after the sound it makes when surfacing.'],
  },
  {
    id: 'snow-leopard',
    kind: 'fauna',
    common_name: 'Snow Leopard',
    scientific_name: 'Panthera uncia',
    description:
      'A pale, heavily furred cat of high Himalayan slopes, rarely seen and able to take prey three times its own weight on near-vertical terrain.',
    image_url: commons('a/a5/Irbis4.JPG/960px-Irbis4.JPG'),
    image_credit: credit('Irbis4.JPG'),
    habitat: 'Mountain',
    region: 'Western Himalayas',
    status: 'VU',
    latitude: 34.15,
    longitude: 77.58,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Carnivora', family: 'Felidae', genus: 'Panthera' },
    ecological_role: 'Apex predator of the alpine zone, regulating wild sheep and goat populations that would otherwise overgraze.',
    dependencies: ['Bharal', 'Himalayan ibex', 'Alpine meadows'],
    field_notes: ['It wraps its long tail around its face for warmth.', 'Snow leopards cannot roar.'],
  },
  {
    id: 'indian-rhinoceros',
    kind: 'fauna',
    common_name: 'Indian Rhinoceros',
    scientific_name: 'Rhinoceros unicornis',
    description:
      'The greater one-horned rhino of the Brahmaputra floodplains. Once reduced to about 200 animals, it has recovered to over 4,000 through strict protection.',
    image_url: commons('7/77/Great-Indian-one-horned-rhinoceros-at-Kaziranga-national-park-in-Assam-India.jpg/960px-Great-Indian-one-horned-rhinoceros-at-Kaziranga-national-park-in-Assam-India.jpg'),
    image_credit: credit('Great-Indian-one-horned-rhinoceros-at-Kaziranga-national-park-in-Assam-India.jpg'),
    habitat: 'Grassland',
    region: 'Northeast India',
    status: 'VU',
    latitude: 26.58,
    longitude: 93.17,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Perissodactyla', family: 'Rhinocerotidae', genus: 'Rhinoceros' },
    ecological_role: 'Mega-grazer that keeps tall floodplain grassland open and spreads seeds in its dung.',
    dependencies: ['Elephant grass', 'Floodplain wetlands'],
    field_notes: ['Kaziranga National Park holds about two thirds of the world population.'],
  },
  {
    id: 'asian-elephant',
    kind: 'fauna',
    common_name: 'Asian Elephant',
    scientific_name: 'Elephas maximus',
    description:
      'The largest land animal in Asia. Herds travel long seasonal routes through forest corridors, eating up to 150 kg of vegetation a day.',
    image_url: commons('9/98/Elephas_maximus_%28Bandipur%29.jpg/960px-Elephas_maximus_%28Bandipur%29.jpg'),
    image_credit: credit('Elephas_maximus_(Bandipur).jpg'),
    habitat: 'Forest',
    region: 'Western Ghats',
    status: 'EN',
    latitude: 11.66,
    longitude: 76.63,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Proboscidea', family: 'Elephantidae', genus: 'Elephas' },
    ecological_role: 'Ecosystem engineer: opens paths and clearings, and carries large seeds for kilometres.',
    dependencies: ['Bamboo', 'Fig trees', 'Forest corridors'],
    field_notes: ['Elephants communicate with rumbles below the range of human hearing.'],
  },
  {
    id: 'great-hornbill',
    kind: 'fauna',
    common_name: 'Great Hornbill',
    scientific_name: 'Buceros bicornis',
    description:
      'A huge fruit-eating bird with a yellow casque. The female seals herself inside a tree cavity to nest, and the male feeds her through a narrow slit.',
    image_url: commons('e/ee/Great_hornbill_Photograph_by_Shantanu_Kuveskar.jpg/960px-Great_hornbill_Photograph_by_Shantanu_Kuveskar.jpg'),
    image_credit: credit('Great_hornbill_Photograph_by_Shantanu_Kuveskar.jpg'),
    habitat: 'Forest',
    region: 'Western Ghats',
    status: 'VU',
    latitude: 10.35,
    longitude: 76.75,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Aves', order: 'Bucerotiformes', family: 'Bucerotidae', genus: 'Buceros' },
    ecological_role: 'Long-distance seed disperser for large-fruited rainforest trees.',
    dependencies: ['Fig trees', 'Old-growth nest trees'],
    field_notes: ['A pair can use the same nest cavity for many years.'],
  },
  {
    id: 'lion-tailed-macaque',
    kind: 'fauna',
    common_name: 'Lion-tailed Macaque',
    scientific_name: 'Macaca silenus',
    description:
      'A shy monkey with a silver mane, found only in fragments of rainforest in the Western Ghats. It spends most of its life in the upper canopy.',
    image_url: commons('c/c3/Lion-tailed_Macaque_in_Bristol_Zoo.jpg/960px-Lion-tailed_Macaque_in_Bristol_Zoo.jpg'),
    image_credit: credit('Lion-tailed_Macaque_in_Bristol_Zoo.jpg'),
    habitat: 'Forest',
    region: 'Western Ghats',
    status: 'EN',
    latitude: 10.26,
    longitude: 76.93,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Primates', family: 'Cercopithecidae', genus: 'Macaca' },
    ecological_role: 'Seed disperser of rainforest fruit trees; avoids disturbed forest, so it marks intact canopy.',
    dependencies: ['Fig trees', 'Jackfruit', 'Unbroken canopy'],
    field_notes: ['Fewer than 4,000 remain in the wild.'],
  },
  {
    id: 'gharial',
    kind: 'fauna',
    common_name: 'Gharial',
    scientific_name: 'Gavialis gangeticus',
    description:
      'A fish-eating crocodilian with a long, thin snout. Adult males grow a bulbous knob on the snout tip called a ghara, after an Indian clay pot.',
    image_url: commons('a/a7/Gharial_%28Gavialis_gangeticus%29_male.jpg/960px-Gharial_%28Gavialis_gangeticus%29_male.jpg'),
    image_credit: credit('Gharial_(Gavialis_gangeticus)_male.jpg'),
    habitat: 'Wetland',
    region: 'Chambal Valley',
    status: 'CR',
    latitude: 26.65,
    longitude: 78.35,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Reptilia', order: 'Crocodylia', family: 'Gavialidae', genus: 'Gavialis' },
    ecological_role: 'Controls fish populations in deep river pools; needs undisturbed sandbanks to nest.',
    dependencies: ['Freshwater fish', 'River sandbanks'],
    field_notes: ['The National Chambal Sanctuary is its most important stronghold.'],
  },
  {
    id: 'nilgiri-tahr',
    kind: 'fauna',
    common_name: 'Nilgiri Tahr',
    scientific_name: 'Nilgiritragus hylocrius',
    description:
      'A stocky mountain goat of the southern Western Ghats, grazing the high grassland that caps the hills above the shola forest.',
    image_url: commons('8/89/Nilgiri_Tahr_at_Eravikulam_National_Park.jpg/960px-Nilgiri_Tahr_at_Eravikulam_National_Park.jpg'),
    image_credit: credit('Nilgiri_Tahr_at_Eravikulam_National_Park.jpg'),
    habitat: 'Grassland',
    region: 'Western Ghats',
    status: 'EN',
    latitude: 10.17,
    longitude: 77.06,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Artiodactyla', family: 'Bovidae', genus: 'Nilgiritragus' },
    ecological_role: 'Main grazer of montane grassland and key prey for leopards and dholes.',
    dependencies: ['Montane grassland', 'Shola forest'],
    field_notes: ['It is the state animal of Tamil Nadu.'],
  },
  {
    id: 'hawksbill-sea-turtle',
    kind: 'fauna',
    common_name: 'Hawksbill Sea Turtle',
    scientific_name: 'Eretmochelys imbricata',
    description:
      'A reef-dwelling sea turtle with a sharp, bird-like beak and an overlapping, patterned shell. It nests on beaches of the Andaman and Lakshadweep islands.',
    image_url: commons('b/b0/Eretmochelys-imbricata-K%C3%A9lonia-2.JPG/960px-Eretmochelys-imbricata-K%C3%A9lonia-2.JPG'),
    image_credit: credit('Eretmochelys-imbricata-Kélonia-2.JPG'),
    habitat: 'Marine',
    region: 'Lakshadweep',
    status: 'CR',
    latitude: 10.57,
    longitude: 72.64,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Reptilia', order: 'Testudines', family: 'Cheloniidae', genus: 'Eretmochelys' },
    ecological_role: 'Eats reef sponges that would otherwise crowd out corals.',
    dependencies: ['Sea sponges', 'Coral reefs', 'Nesting beaches'],
    field_notes: ['Its shell was historically the main source of “tortoiseshell”.'],
  },
  {
    id: 'indian-pangolin',
    kind: 'fauna',
    common_name: 'Indian Pangolin',
    scientific_name: 'Manis crassicaudata',
    description:
      'A nocturnal, scale-covered anteater that rolls into a ball when threatened. It is one of the most trafficked mammals in the world.',
    image_url: commons('3/30/Scaly_ant_eater_by_Dushy_Ranetunge_2.jpg/960px-Scaly_ant_eater_by_Dushy_Ranetunge_2.jpg'),
    image_credit: credit('Scaly_ant_eater_by_Dushy_Ranetunge_2.jpg'),
    habitat: 'Forest',
    region: 'Central India',
    status: 'EN',
    latitude: 21.15,
    longitude: 79.09,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Pholidota', family: 'Manidae', genus: 'Manis' },
    ecological_role: 'Natural pest control: a single pangolin eats tens of millions of ants and termites a year.',
    dependencies: ['Termites', 'Ants'],
    field_notes: ['Pangolins have no teeth; they swallow small stones to grind food.'],
  },
  {
    id: 'great-indian-bustard',
    kind: 'fauna',
    common_name: 'Great Indian Bustard',
    scientific_name: 'Ardeotis nigriceps',
    description:
      'One of the heaviest flying birds, striding through dry grassland of the Thar. Collisions with power lines are now its leading cause of death.',
    image_url: commons('3/34/Ardeotis_nigriceps%2C_Desert_National_Park%2C_Rajasthan%2C_India_1.jpg/960px-Ardeotis_nigriceps%2C_Desert_National_Park%2C_Rajasthan%2C_India_1.jpg'),
    image_credit: credit('Ardeotis_nigriceps,_Desert_National_Park,_Rajasthan,_India_1.jpg'),
    habitat: 'Grassland',
    region: 'Thar Desert',
    status: 'CR',
    latitude: 26.93,
    longitude: 70.9,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Aves', order: 'Otidiformes', family: 'Otididae', genus: 'Ardeotis' },
    ecological_role: 'Flagship of arid grasslands; eats grasshoppers and other crop pests.',
    dependencies: ['Grasshoppers', 'Arid grassland'],
    field_notes: ['Fewer than 150 birds are thought to survive.'],
  },
  {
    id: 'purple-frog',
    kind: 'fauna',
    common_name: 'Purple Frog',
    scientific_name: 'Nasikabatrachus sahyadrensis',
    description:
      'A bloated, burrowing frog that lives underground for most of the year and surfaces for only a few days of monsoon to breed.',
    image_url: commons('0/08/Nasikabatrachus_sahyadrensis.jpg/960px-Nasikabatrachus_sahyadrensis.jpg'),
    image_credit: credit('Nasikabatrachus_sahyadrensis.jpg'),
    habitat: 'Forest',
    region: 'Western Ghats',
    status: 'EN',
    latitude: 9.85,
    longitude: 76.97,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Amphibia', order: 'Anura', family: 'Nasikabatrachidae', genus: 'Nasikabatrachus' },
    ecological_role: 'Underground termite predator; its lineage split from its closest relatives in the Seychelles over 100 million years ago.',
    dependencies: ['Termites', 'Monsoon streams'],
    field_notes: ['It was only described by science in 2003.'],
  },
  {
    id: 'dugong',
    kind: 'fauna',
    common_name: 'Dugong',
    scientific_name: 'Dugong dugon',
    description:
      'A slow, gentle marine mammal that grazes seagrass meadows in shallow coastal water. India’s largest populations are in the Gulf of Mannar and Palk Bay.',
    image_url: commons('4/42/Dugong.JPG/960px-Dugong.JPG'),
    image_credit: credit('Dugong.JPG'),
    habitat: 'Marine',
    region: 'Gulf of Mannar',
    status: 'VU',
    latitude: 9.12,
    longitude: 79.15,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Sirenia', family: 'Dugongidae', genus: 'Dugong' },
    ecological_role: 'Grazing keeps seagrass meadows productive, which in turn shelter juvenile fish.',
    dependencies: ['Seagrass meadows'],
    field_notes: ['Dugongs are more closely related to elephants than to whales.'],
  },
  {
    id: 'blackbuck',
    kind: 'fauna',
    common_name: 'Blackbuck',
    scientific_name: 'Antilope cervicapra',
    description:
      'A fast antelope of open plains. Males turn nearly black with age and carry long spiralled horns. It has rebounded where local communities protect it.',
    image_url: commons('5/5e/Blackbuck_male_female.jpg/960px-Blackbuck_male_female.jpg'),
    image_credit: credit('Blackbuck_male_female.jpg'),
    habitat: 'Grassland',
    region: 'Western India',
    status: 'LC',
    latitude: 22.05,
    longitude: 72.03,
    taxonomy: { kingdom: 'Animalia', phylum: 'Chordata', class: 'Mammalia', order: 'Artiodactyla', family: 'Bovidae', genus: 'Antilope' },
    ecological_role: 'Grazer of short grassland and prey for wolves.',
    dependencies: ['Arid grassland'],
    field_notes: ['It can run at over 80 km/h.'],
  },

  // ---------------------------------------------------------------- Flora
  {
    id: 'banyan',
    kind: 'flora',
    common_name: 'Banyan',
    scientific_name: 'Ficus benghalensis',
    description:
      'India’s national tree. Aerial roots drop from its branches and thicken into new trunks, so one banyan can spread over an acre and behave like a small forest.',
    image_url: commons('9/9f/Great_banyan_tree_kol.jpg/960px-Great_banyan_tree_kol.jpg'),
    image_credit: credit('Great_banyan_tree_kol.jpg'),
    habitat: 'Forest',
    region: 'Central India',
    status: 'LC',
    latitude: 22.57,
    longitude: 88.36,
    taxonomy: { kingdom: 'Plantae', phylum: 'Tracheophyta', class: 'Magnoliopsida', order: 'Rosales', family: 'Moraceae', genus: 'Ficus' },
    ecological_role: 'A keystone food plant: it fruits when little else does, feeding hornbills, monkeys, bats and civets through the lean season.',
    dependencies: ['Fig wasps', 'Fruit bats'],
    aliases: ['Fig trees', 'Fig tree', 'Figs'],
    field_notes: ['Each fig species is pollinated by its own species of wasp.', 'The Great Banyan in Kolkata has more than 3,000 aerial-root trunks.'],
  },
  {
    id: 'sal-tree',
    kind: 'flora',
    common_name: 'Sal',
    scientific_name: 'Shorea robusta',
    description:
      'The dominant hardwood of central and northern Indian forests, forming near-pure stands that define the habitat tigers and elephants move through.',
    image_url: commons('f/fd/Shorea_robusta.jpg/960px-Shorea_robusta.jpg'),
    image_credit: credit('Shorea_robusta.jpg'),
    habitat: 'Forest',
    region: 'Central India',
    status: 'LC',
    latitude: 23.5,
    longitude: 80.5,
    taxonomy: { kingdom: 'Plantae', phylum: 'Tracheophyta', class: 'Magnoliopsida', order: 'Malvales', family: 'Dipterocarpaceae', genus: 'Shorea' },
    ecological_role: 'Structural species of the forest: its canopy and deep leaf litter set the conditions every other forest species lives in.',
    dependencies: ['Monsoon rains', 'Leaf litter fungi'],
    aliases: ['Sal forest', 'Sal Tree'],
    field_notes: ['Sal is slow to burn, so sal forest resists fire better than surrounding scrub.'],
  },
  {
    id: 'indian-thorny-bamboo',
    kind: 'flora',
    common_name: 'Indian Thorny Bamboo',
    scientific_name: 'Bambusa bambos',
    description:
      'A giant clumping grass that can add nearly a metre of height in a day, then flowers once after decades and dies.',
    image_url: commons('b/be/Bambusa_bamus.JPG/960px-Bambusa_bamus.JPG'),
    image_credit: credit('Bambusa_bamus.JPG'),
    habitat: 'Forest',
    region: 'Western Ghats',
    status: 'LC',
    latitude: 11.4,
    longitude: 76.7,
    taxonomy: { kingdom: 'Plantae', phylum: 'Tracheophyta', class: 'Liliopsida', order: 'Poales', family: 'Poaceae', genus: 'Bambusa' },
    ecological_role: 'Fast-growing food and cover for elephants, gaur and red pandas; its clumps stabilise stream banks.',
    dependencies: ['Monsoon rains', 'Stream banks'],
    aliases: ['Bamboo'],
    field_notes: ['A whole bamboo stand flowers at once, then dies together — gregarious flowering.', 'Mass flowering releases so much seed that rat populations explode afterwards.'],
  },
  {
    id: 'tree-rhododendron',
    kind: 'flora',
    common_name: 'Tree Rhododendron',
    scientific_name: 'Rhododendron arboreum',
    description:
      'A Himalayan tree that covers whole slopes in red flowers in spring, growing at altitudes where few other broadleaf trees survive.',
    image_url: commons('c/c9/Lali_Gurans.JPG/960px-Lali_Gurans.JPG'),
    image_credit: credit('Lali_Gurans.JPG'),
    habitat: 'Mountain',
    region: 'Eastern Himalayas',
    status: 'LC',
    latitude: 27.4,
    longitude: 88.5,
    taxonomy: { kingdom: 'Plantae', phylum: 'Tracheophyta', class: 'Magnoliopsida', order: 'Ericales', family: 'Ericaceae', genus: 'Rhododendron' },
    ecological_role: 'Early-season nectar source for Himalayan bees and sunbirds, and shelter canopy for red pandas.',
    dependencies: ['Himalayan bees', 'Sunbirds', 'Acidic mountain soil'],
    aliases: ['Rhododendron forest', 'Rhododendron'],
    field_notes: ['It is the state tree of Uttarakhand and the national flower of Nepal.'],
  },
  {
    id: 'sundari',
    kind: 'flora',
    common_name: 'Sundari',
    scientific_name: 'Heritiera fomes',
    description:
      'The mangrove that gives the Sundarbans its name. It breathes through pencil-like roots that push up out of the tidal mud.',
    image_url: commons('4/40/Sundarbans_02.jpg/960px-Sundarbans_02.jpg'),
    image_credit: credit('Sundarbans_02.jpg'),
    habitat: 'Wetland',
    region: 'Ganges Basin',
    status: 'EN',
    latitude: 21.95,
    longitude: 89.18,
    taxonomy: { kingdom: 'Plantae', phylum: 'Tracheophyta', class: 'Magnoliopsida', order: 'Malvales', family: 'Malvaceae', genus: 'Heritiera' },
    ecological_role: 'Holds the delta together: mangrove roots trap sediment, break storm surges and shelter juvenile fish.',
    dependencies: ['Tidal mudflats', 'Brackish water'],
    aliases: ['Mangrove forest', 'Mangroves'],
    field_notes: ['Rising salinity from reduced river flow is killing sundari stands across the delta.'],
  },
  {
    id: 'indian-sandalwood',
    kind: 'flora',
    common_name: 'Indian Sandalwood',
    scientific_name: 'Santalum album',
    description:
      'A small hemiparasitic tree that taps the roots of neighbouring plants for water and nutrients, and lays down fragrant heartwood over decades.',
    image_url: commons('e/e4/Santalum_album_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-128.jpg/960px-Santalum_album_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-128.jpg'),
    image_credit: credit('Santalum_album_-_Köhler–s_Medizinal-Pflanzen-128.jpg'),
    habitat: 'Forest',
    region: 'Western Ghats',
    status: 'VU',
    latitude: 12.3,
    longitude: 76.65,
    taxonomy: { kingdom: 'Plantae', phylum: 'Tracheophyta', class: 'Magnoliopsida', order: 'Santalales', family: 'Santalaceae', genus: 'Santalum' },
    ecological_role: 'Its fruit feeds birds that scatter the seed; it cannot grow past seedling stage without a host plant.',
    dependencies: ['Host tree roots', 'Seed-dispersing birds'],
    field_notes: ['A tree needs roughly 15 years before its heartwood is worth harvesting, which is why poaching targets mature trees.'],
  },
  {
    id: 'khasi-pitcher-plant',
    kind: 'flora',
    common_name: 'Khasi Pitcher Plant',
    scientific_name: 'Nepenthes khasiana',
    description:
      'India’s only pitcher plant, found solely in Meghalaya. Its leaf tips form fluid-filled traps that digest insects to make up for poor soil.',
    image_url: commons('9/9b/Nepenthes_khasiana.jpg/960px-Nepenthes_khasiana.jpg'),
    image_credit: credit('Nepenthes_khasiana.jpg'),
    habitat: 'Mountain',
    region: 'Northeast India',
    status: 'EN',
    latitude: 25.5,
    longitude: 91.7,
    taxonomy: { kingdom: 'Plantae', phylum: 'Tracheophyta', class: 'Magnoliopsida', order: 'Caryophyllales', family: 'Nepenthaceae', genus: 'Nepenthes' },
    ecological_role: 'A carnivorous plant of nutrient-poor slopes; its pitchers are a miniature habitat for specialised insect larvae.',
    dependencies: ['Insects', 'Acidic bog soil'],
    field_notes: ['Locally called “monkey cups”.', 'Collection for trade and quarrying have pushed it to a handful of sites.'],
  },
  {
    id: 'ashoka-tree',
    kind: 'flora',
    common_name: 'Ashoka Tree',
    scientific_name: 'Saraca asoca',
    description:
      'An evergreen understorey tree of moist Western Ghats forest, flowering in dense orange clusters directly off its branches.',
    image_url: commons('2/2f/Sita-Ashok_%28Saraca_asoca%29_flowers_in_Kolkata_W_IMG_4146.jpg/960px-Sita-Ashok_%28Saraca_asoca%29_flowers_in_Kolkata_W_IMG_4146.jpg'),
    image_credit: credit('Sita-Ashok_(Saraca_asoca)_flowers_in_Kolkata_W_IMG_4146.jpg'),
    habitat: 'Forest',
    region: 'Western Ghats',
    status: 'VU',
    latitude: 13.3,
    longitude: 74.9,
    taxonomy: { kingdom: 'Plantae', phylum: 'Tracheophyta', class: 'Magnoliopsida', order: 'Fabales', family: 'Fabaceae', genus: 'Saraca' },
    ecological_role: 'Night-flowering nectar source for moths, and a shade tree along forest streams.',
    dependencies: ['Pollinating moths', 'Stream banks'],
    field_notes: ['Heavy bark collection for medicine is a main reason wild populations are shrinking.'],
  },
  {
    id: 'sickle-seagrass',
    kind: 'flora',
    common_name: 'Sickle Seagrass',
    scientific_name: 'Thalassia hemprichii',
    description:
      'A true flowering plant that lives fully submerged in shallow sea, spreading through sand by underground stems to form dense meadows.',
    image_url: commons('f/f7/Thalassia_hemprichii.jpg/960px-Thalassia_hemprichii.jpg'),
    image_credit: credit('Thalassia_hemprichii.jpg'),
    habitat: 'Marine',
    region: 'Gulf of Mannar',
    status: 'LC',
    latitude: 9.2,
    longitude: 79.2,
    taxonomy: { kingdom: 'Plantae', phylum: 'Tracheophyta', class: 'Liliopsida', order: 'Alismatales', family: 'Hydrocharitaceae', genus: 'Thalassia' },
    ecological_role: 'The entire diet of dugongs and turtles here, plus a nursery for reef fish and a large store of carbon in its sediment.',
    dependencies: ['Clear shallow water', 'Sunlight'],
    aliases: ['Seagrass meadows', 'Seagrass'],
    field_notes: ['Seagrass meadows lock away carbon far faster per hectare than rainforest.'],
  },
  {
    id: 'neem',
    kind: 'flora',
    common_name: 'Neem',
    scientific_name: 'Azadirachta indica',
    description:
      'A drought-hardy evergreen planted across Indian villages and roadsides, whose leaves and seeds contain natural insect-repelling compounds.',
    image_url: commons('7/7b/Neem_Tree_in_Rajasthan%2C_India.jpg/960px-Neem_Tree_in_Rajasthan%2C_India.jpg'),
    image_credit: credit('Neem_Tree_in_Rajasthan,_India.jpg'),
    habitat: 'Urban',
    region: 'Western India',
    status: 'LC',
    latitude: 26.9,
    longitude: 75.8,
    taxonomy: { kingdom: 'Plantae', phylum: 'Tracheophyta', class: 'Magnoliopsida', order: 'Sapindales', family: 'Meliaceae', genus: 'Azadirachta' },
    ecological_role: 'Shade and roosting tree in dry, settled landscapes where little else grows; its fruit feeds birds and bats.',
    dependencies: ['Seed-dispersing birds', 'Arid grassland'],
    field_notes: ['Azadirachtin, its active compound, disrupts insect moulting rather than poisoning outright.'],
  },
  {
    id: 'beddomes-cycad',
    kind: 'flora',
    common_name: 'Beddome’s Cycad',
    scientific_name: 'Cycas beddomei',
    description:
      'A palm-like relic of a lineage older than flowering plants, restricted to a small stretch of dry hills in the Eastern Ghats.',
    image_url: commons('9/99/Cycas_beddomei_03.jpg/960px-Cycas_beddomei_03.jpg'),
    image_credit: credit('Cycas_beddomei_03.jpg'),
    habitat: 'Forest',
    region: 'Eastern Ghats',
    status: 'CR',
    latitude: 13.63,
    longitude: 79.42,
    taxonomy: { kingdom: 'Plantae', phylum: 'Cycadophyta', class: 'Cycadopsida', order: 'Cycadales', family: 'Cycadaceae', genus: 'Cycas' },
    ecological_role: 'Hosts nitrogen-fixing bacteria in specialised roots, enriching the thin soil of rocky slopes.',
    dependencies: ['Rocky hill slopes', 'Pollinating beetles'],
    field_notes: ['Cycads are pollinated by beetles, a system older than bees.', 'Collection of its male cones for medicine has stripped many slopes.'],
  },
  {
    id: 'bourdillons-dipterocarp',
    kind: 'flora',
    common_name: 'Bourdillon’s Dipterocarp',
    scientific_name: 'Dipterocarpus bourdillonii',
    description:
      'A towering rainforest tree of the southern Western Ghats, down to scattered survivors in fragmented valleys.',
    image_url: commons('b/bb/Dipterocarpus_bourdillonii_01.JPG/960px-Dipterocarpus_bourdillonii_01.JPG'),
    image_credit: credit('Dipterocarpus_bourdillonii_01.JPG'),
    habitat: 'Forest',
    region: 'Western Ghats',
    status: 'CR',
    latitude: 9.5,
    longitude: 77.1,
    taxonomy: { kingdom: 'Plantae', phylum: 'Tracheophyta', class: 'Magnoliopsida', order: 'Malvales', family: 'Dipterocarpaceae', genus: 'Dipterocarpus' },
    ecological_role: 'Emergent canopy tree: its crown is the upper storey that hornbills and lion-tailed macaques depend on.',
    dependencies: ['Monsoon rains', 'Unbroken canopy'],
    aliases: ['Rainforest canopy'],
    field_notes: ['Its winged seeds spin to the ground and stay viable only a few days.'],
  },
];
